require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*

Stule/Documentation:
  Exclude:
    - app/helpers/**/*
    - app/controllers/**/*
    - app/mailers/**/*
    - app/models/**/*
    - app/lib/**/*
    - db/migrate/**/*
    - config/application.rb
    - test/**/*