require: "rubocop-rails"

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/initializers/simple_form_bootstrap.rb
    - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb

Stule/Documentation:
  Exclude:
    - app/helpers/**/*
    - app/controllers/**/*
    - app/mailers/**/*
    - app/models/**/*
    - app/lib/**/*
    - app/jobs/**/*
    - db/migrate/**/*
    - config/application.rb
    - config/initializers/**/*
    - test/**/*